/**
 * Generate the service worker's precache list from the actual build output.
 *
 * Hand-maintaining a list of files to cache is a bug waiting to happen: the
 * bundler renames every chunk on every content change, so a hand-written list
 * is stale the moment anything is edited, and the failure mode is the worst
 * kind — it works online and breaks offline, which is exactly the case nobody
 * tests. So the list is read off dist/ after the build.
 *
 * The cache name embeds a hash of that list, so a new build is a new cache and
 * the old one is deleted on activate. Without it a returning visitor would be
 * served last week's bundle forever.
 *
 * Usage: node scripts/build-sw.mjs [distDir]
 */
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve, relative } from 'node:path';

/** Everything worth precaching. Source maps are not. */
const PRECACHE_EXTENSIONS = new Set([
  '.html',
  '.js',
  '.css',
  '.webp',
  '.png',
  '.jpg',
  '.svg',
  '.woff',
  '.woff2',
  '.json',
  '.webmanifest',
  '.ico',
]);

export async function collectAssets(dir, base = dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await collectAssets(full, base)));
      continue;
    }
    if (entry.name.endsWith('.map')) continue;
    if (entry.name === 'sw.js') continue;
    // The 2021 worker's kill switch: served, never precached.
    if (entry.name === 'serviceworker.js') continue;
    const ext = entry.name.slice(entry.name.lastIndexOf('.'));
    if (!PRECACHE_EXTENSIONS.has(ext)) continue;
    // Relative, with no leading slash. vite.config.ts builds with `base: './'`
    // so the app can be served from any path; an absolute precache list would
    // quietly contradict that and break exactly one deployment shape.
    out.push(relative(base, full).split(/[\\/]/).join('/'));
  }
  return out.sort();
}

export function renderServiceWorker(assets, version) {
  return `/* Generated by scripts/build-sw.mjs. Do not edit. */
const CACHE = 'starship-${version}';

/*
  Paths are relative to the worker's own scope, because the app is built with
  vite's \`base: './'\` and can therefore be served from any path. Resolving them
  here is what lets the same build work at the domain root and in a subdirectory.
*/
const PATHS = ${JSON.stringify(assets, null, 2)};
const ASSETS = PATHS.map((path) => new URL(path, self.registration.scope).href);
const SHELL = new URL('index.html', self.registration.scope).href;

self.addEventListener('install', (event) => {
  // Every asset, up front. The point of this file is that a flight started
  // offline behaves exactly like one started online, which means nothing may be
  // fetched lazily at a moment when there is no network -- including the black
  // box chunk, which is lazy on purpose and precached anyway.
  // No skipWaiting: a new build waits until the last tab on the old one closes.
  // Taking over at once would delete the cache an open tab's lazy chunks
  // (the black box) still need, and they would 404 for the rest of that visit.
  // A first install has no old worker to wait for, so it activates at once.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

/*
  Only this app's own superseded caches, and the 2021 game's ('v2'). The Pages
  origin is shared with every other project site on it, and their caches are
  not ours to delete.
*/
function isStale(key) {
  return key !== CACHE && (key.startsWith('starship-') || key === 'v2');
}

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter(isStale).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Cache first. This is a simulator, not a feed: the assets are immutable
  // within a build, and going to the network first would make every load wait
  // on a round trip to learn nothing.
  /*
    ignoreVary matters. cache.addAll() stores each response keyed by a request
    it builds itself, and a server that sends a Vary header — vite preview sends
    \`Vary: Origin\` — makes the later page request fail to match the stored key.
    The symptom is the worst possible one: everything works online, and offline
    every asset misses the cache and 504s. ignoreSearch is belt and braces for
    cache-busting query strings.
  */
  const MATCH = { ignoreVary: true, ignoreSearch: true };

  event.respondWith(
    caches.match(request, MATCH).then((hit) => {
      if (hit) return hit;
      // A navigation to any path is the app shell -- there is one page.
      if (request.mode === 'navigate') {
        return caches.match(SHELL, MATCH).then((shell) => shell ?? fetch(request));
      }
      return fetch(request).catch(() => new Response('', { status: 504 }));
    }),
  );
});
`;
}

export async function buildServiceWorker(distDir) {
  const dist = resolve(distDir);
  const assets = await collectAssets(dist);
  if (assets.length === 0) throw new Error(`no assets found in ${dist}`);

  const hashes = createHash('sha256');
  for (const asset of assets) {
    hashes.update(asset);
    hashes.update(await readFile(join(dist, asset)));
  }
  const version = hashes.digest('hex').slice(0, 12);

  await writeFile(join(dist, 'sw.js'), renderServiceWorker(assets, version), 'utf8');
  return { assets, version };
}

const invokedDirectly = process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop());
if (invokedDirectly) {
  const { assets, version } = await buildServiceWorker(process.argv[2] ?? 'dist');
  console.log(`service worker: ${assets.length} assets precached, version ${version}`);
}
